### PR TITLE
Adding University of Cambridge

### PR DESCRIPTION
**Pull request by KevinPayravi**
IP ranges from:
http://www.ucs.cam.ac.uk/network/ip/camnets.html

### CODE REVIEW

**Comment by KevinPayravi** [comment]
The link provided also shows a IPv6 address: 2001:630:210::/44

Is this supported, and is it formatted properly?

**Comment by eeevanbbb** [comment]
Re IPv6: In _theory_, I see no reason why it wouldn't be supported, but glancing at the live feed of Wikipedia edits I didn't see any IPv6 addresses, so I can't say for certain.

**Comment by KevinPayravi** [comment]
I know Wikipedia supports IPv6 editing, just wasn't sure if the range was
properly formatted. I imagine it should be fine too.

**Comment by eeevanbbb** [comment]
The docs for the python library I'm using are here (See IPNetwork() and IPAddress()):

https://pythonhosted.org/netaddr/api.html

It looks like that's the right format. Again, in _theory_ it should work, but it might be a while before we could be certain.

**Pull request merged**
